declare global {
  type IProvidedUser = {
    provider: string; // The provider with which the user authenticated (facebook, twitter, etc.).
    id: string; // A unique identifier for the user, as generated by the service provider.
    displayName: string; // The name of this user, suitable for display.
    name: {
      familyName: string; // The family name of this user, or "last name" in most Western languages.
      givenName: string; // The given name of this user, or "first name" in most Western languages.
      middleName: string; //The middle name of this user.
    };
    emails: {
      value: string; // The actual email address.
      type: string; // // The type of email address (home, work, etc.).
    }[];
    photos: {
      value: string;
    }[]; // The URL of the image.
  };

  type IUser = IProvidedUser & {
    organizations: string[];
    role: number;
  };
}

export {};
